name: automerge
on:
  pull_request:
    types:
      # Action does not start before the PR has the automerge label
      - labeled
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.5"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          LOG: "DEBUG"
          MERGE_DELETE_BRANCH: "true"
