name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - split-repos
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout frontend
        uses: actions/checkout@v2
        with:
          repository: sine-fdn/pact-catalog-web-app
          token: ${{ secrets.PAT }}
          ref: repo-split
      # - name: Install Vercel CLI
      #   run: |
      #     npm install --global vercel@latest
      #     ls -alh
      # - name: Pull Vercel Environment Information
      #   working-directory: ./app
      #   run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      # - name: Build Project Artifacts
      #   working-directory: ./app
      #   run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      # - name: Deploy Project Artifacts to Vercel
      #   working-directory: ./app
      #   run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
